spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fire-comp}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:fire-comp}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:firecomp2025}}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
